<?php

namespace Febis\SimpleTca;

use Febis\SimpleTca\Data\ItemConfig;
use Febis\SimpleTca\Data\TcaDefinitionData;
use Febis\SimpleTca\Data\TsConfig\FceGroup;
use Febis\SimpleTca\Data\TsConfig\TsConfigDataHandling;
use Febis\SimpleTca\Data\Typoscript\TyposcriptDataHandling;
use Febis\SimpleTca\Exception\CacheInstanceException;
use Febis\SimpleTca\Exception\CallstackExtractionException;
use Febis\SimpleTca\Exception\TsConfigExistsException;
use Febis\SimpleTca\FceGenerator\FceGenerator;
use Febis\SimpleTca\FceGenerator\Showitem\Mode;
use Febis\SimpleTca\TcaBuilder\TcaBuilder;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class TcaGenerator extends ShortcutImplementation
{
    use ConfigTrait;

    protected static ?TcaDefinitionData $tcaDefinitionDataInstance = null;
    protected static ?TsConfigDataHandling $tsConfigData = null;
    protected static ?TyposcriptDataHandling $typoscriptData = null;
    protected static ?ItemConfig $tmpItemConfig = null;

    private function __construct()
    {
    }

    /**
     * @throws CallstackExtractionException
     */
    public static function createTca(string $table = null): TcaBuilder
    {
        return new TcaBuilder($table ?? static::getConfig()->getTablename());
    }

    /**
     * @param string $identifier
     * @param string $cTypeLabel
     * @param string $icon
     * @param array $palettes
     * @param array $columns
     * @param string $showItem
     * @param Mode $showitemMode
     * @param array $columnsOverrides
     * @param bool $autogenerateTyposcript
     * @param bool $autogenerateTsConfig
     * @param bool $autogenerateDataProcessors only available if typoscript is also generated
     * @return FceGenerator
     * @throws CallstackExtractionException
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     * @SuppressWarnings(PHPMD.BooleanArgumentFlag)
     */
    public static function createFCE(
        string $identifier,
        string $cTypeLabel = '',
        string $icon = '',
        array $palettes = [],
        array $columns = [],
        string $showItem = '',
        Mode $showitemMode = Mode::Default,
        array $columnsOverrides = [],
        bool $autogenerateTyposcript = true,
        bool $autogenerateTsConfig = true,
        bool $autogenerateDataProcessors = true,
    ): FceGenerator {
        $extKey = self::getConfig()->getExtkey();
        self::$tmpItemConfig = GeneralUtility::makeInstance(ItemConfig::class, $identifier);

        return GeneralUtility::makeInstance(
            FceGenerator::class,
            $extKey,
            $identifier,
            $cTypeLabel,
            $icon,
            $palettes,
            $columns,
            $showItem,
            $showitemMode,
            $columnsOverrides,
            $autogenerateTsConfig,
            $autogenerateTyposcript,
            $autogenerateDataProcessors,
        );
    }

    /**
     * @throws TsConfigExistsException
     * @throws CacheInstanceException
     */
    public static function overrideDefaultTsConfigFceGroup(string $header, string $show = '*'): void
    {
        static::getTsConfigData()->addFceGroup('default', new FceGroup('group', $header, $show), true);
    }

    public static function getTcaDefinitionDataInstance(): TcaDefinitionData
    {
        if (static::$tcaDefinitionDataInstance === null) {
            static::$tcaDefinitionDataInstance = GeneralUtility::makeInstance(TcaDefinitionData::class);
        }
        return static::$tcaDefinitionDataInstance;
    }

    /**
     * @throws TsConfigExistsException
     * @throws CacheInstanceException
     */
    public static function getTsConfigData(): TsConfigDataHandling
    {
        if (static::$tsConfigData === null) {
            static::$tsConfigData = GeneralUtility::makeInstance(TsConfigDataHandling::class);

            if (!static::$tsConfigData->hasFceGroup('default')) {
                static::$tsConfigData->addFceGroup('default', new FceGroup('default', 'Default'));
            }
        }
        return static::$tsConfigData;
    }

    public static function getTyposcriptData(): TyposcriptDataHandling
    {
        if (static::$typoscriptData === null) {
            static::$typoscriptData = GeneralUtility::makeInstance(TyposcriptDataHandling::class);
        }
        return static::$typoscriptData;
    }

    public static function getItemConfig(): ItemConfig
    {
        return static::$tmpItemConfig;
    }

    public static function resetItemConfig(): void
    {
        static::$tmpItemConfig = null;
    }

    /**
     * @throws CallstackExtractionException
     */
    public static function translate(string $key): string
    {
        $conf = static::getConfig();
        $identifier = !empty(self::$tmpItemConfig?->identifier ?? '') ? self::$tmpItemConfig->identifier . '.' : '';
        return $conf->ll() . $conf->getTablename() . '.' . $identifier . $key;
    }

    /**
     * @throws CallstackExtractionException
     */
    public function setDefaultLocalizationFile(string $filename)
    {
        self::getConfig()->setDefaultLocalizationFile($filename);
    }
}
